### ISSUE TITLE
Ajout Password & Username dans l'entité Personne

### ISSUE THREAD

**Issue by J-Dudek** [AcLabM1/DNE-API#68]
Suite point demande de début de semaine et revérification MCD : ajouter champ Password & Username dans l'entité Personne.

**Comment by J-Dudek** [comment]
StackTrace actuelle causée par l'heritage et le mapping dto. Si vous pouvez jeter un oeil @MorganLmd @PierreDarcas 
Trace obtenue en faisant un login avec le Responsable, je n'ai pas eu le temps de tester les autres cas mais il y a de la matière dans le Dataloader.
```java
1) The destination property com.aclab.dne.dto.ResponsableFormationDTO.setIdResponsableFormation() matches multiple source property hierarchies:

	com.aclab.dne.model.Personne.getIdPersonne()
	com.aclab.dne.model.InterneUniv.getIdUniv()

1 error] with root cause

org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) The destination property com.aclab.dne.dto.ResponsableFormationDTO.setIdResponsableFormation() matches multiple source property hierarchies:

	com.aclab.dne.model.Personne.getIdPersonne()
	com.aclab.dne.model.InterneUniv.getIdUniv()

1 error
	at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241) ~[modelmapper-2.3.8.jar:na]
	at org.modelmapper.internal.ImplicitMappingBuilder.matchDestination(ImplicitMappingBuilder.java:158) ~[modelmapper-2.3.8.jar:na] ```
